#!/usr/bin/env python3
"""
select_blabber_asset_triphone.py

Selector for blabber libraries generated by deep_phone_candidate_stack_kokoro.py.

This is compatible with the new triphone-style output:

  {
    "blabber_assets": [...],
    "assets": [...],
    "search_index": {...},
    "library": {
      "assets": [...],
      "search_index": {...}
    }
  }

It also tolerates older/raw candidate-only JSON by converting candidates into
minimal assets on load.

Search strategy, similar to global phoneme augmentation lookup:
  1. Filter by target word, optional voice, optional level range.
  2. Score exact full-phone match.
  3. Score triphone overlap.
  4. Score biphone overlap.
  5. Score loose phone inventory overlap.
  6. Add suitability/neural/phone similarity bonuses.
  7. Return top-k assets.

Examples:

  python select_blabber_asset_triphone.py no_blabber_triphone_rule_only.json \
    --word no \
    --phones N AH W OW \
    --top-k 5

  python select_blabber_asset_triphone.py no_blabber_triphone_rule_only.json \
    --word no \
    --triphones '<s>|N|AH,N|AH|W,AH|W|OW,W|OW|</s>' \
    --top-k 5

  python select_blabber_asset_triphone.py no_blabber_triphone_rule_only.json \
    --word no \
    --phones N OW \
    --max-level 0.1
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


VOICE_ALIASES = {
    "female": "woman",
    "woman": "woman",
    "male": "man",
    "man": "man",
}


GENDER_ALIASES = {
    "female": "female",
    "woman": "female",
    "male": "male",
    "man": "male",
}


def phone_sequence_key(phones: list[str]) -> str:
    return " ".join(phones)


def triphone_keys(
    phones: list[str],
    left_boundary: str = "<s>",
    right_boundary: str = "</s>",
) -> list[str]:
    padded = [left_boundary] + list(phones) + [right_boundary]
    return [
        f"{padded[i]}|{padded[i + 1]}|{padded[i + 2]}"
        for i in range(len(padded) - 2)
    ]


def biphone_keys(
    phones: list[str],
    left_boundary: str = "<s>",
    right_boundary: str = "</s>",
) -> list[str]:
    padded = [left_boundary] + list(phones) + [right_boundary]
    return [
        f"{padded[i]}|{padded[i + 1]}"
        for i in range(len(padded) - 1)
    ]


def phone_inventory_keys(phones: list[str]) -> list[str]:
    return sorted(set(phones))


def parse_phone_args(values: list[str] | None) -> list[str]:
    if not values:
        return []
    if len(values) == 1:
        # Allow either "N AH W OW" or "N,AH,W,OW".
        text = values[0].replace(",", " ").strip()
        return [x for x in text.split() if x]
    return values


def parse_key_csv(text: str | None) -> list[str]:
    if not text:
        return []
    return [x.strip() for x in text.split(",") if x.strip()]


def clamp_unit(value: float) -> float:
    return max(0.0, min(1.0, float(value)))


def normalize_voice_mode(value: str | None) -> str | None:
    if value is None:
        return None
    normalized = str(value).strip().lower()
    if not normalized:
        return None
    return VOICE_ALIASES.get(normalized, normalized)


def normalize_gender(value: str | None) -> str | None:
    if value is None:
        return None
    normalized = str(value).strip().lower()
    if not normalized:
        return None
    return GENDER_ALIASES.get(normalized, normalized)


def gender_to_voice_mode(value: str | None) -> str | None:
    gender = normalize_gender(value)
    if gender == "female":
        return "woman"
    if gender == "male":
        return "man"
    return None


def infer_voice_mode_from_path(path_value: Any) -> str | None:
    if not path_value:
        return None
    parts = Path(str(path_value).replace("\\", "/")).parts
    for part in parts:
        voice = normalize_voice_mode(part)
        if voice in {"woman", "man"}:
            return voice
    return None


def asset_voice_mode(asset: dict[str, Any]) -> str | None:
    explicit = normalize_voice_mode(asset.get("voice_mode"))
    if explicit in {"woman", "man"}:
        return explicit

    from_gender = gender_to_voice_mode(asset.get("gender"))
    if from_gender is not None:
        return from_gender

    for key in ("audio_path", "wav_path", "output_audio_path"):
        inferred = infer_voice_mode_from_path(asset.get(key))
        if inferred is not None:
            return inferred

    # `voice` is often just "piper", so only use it when it is a real bank name.
    from_voice = normalize_voice_mode(asset.get("voice"))
    if from_voice in {"woman", "man"}:
        return from_voice
    return None


def jaccard(a: set[str], b: set[str]) -> float:
    if not a and not b:
        return 1.0
    if not a or not b:
        return 0.0
    return len(a & b) / max(1, len(a | b))


def overlap_recall(query: set[str], candidate: set[str]) -> float:
    """How much of the query is covered by the candidate."""
    if not query:
        return 0.0
    return len(query & candidate) / max(1, len(query))


def normalize_asset_from_candidate(c: dict[str, Any], canonical_phones: list[str] | None, idx: int) -> dict[str, Any]:
    phones = list(c.get("phones") or [])
    canonical = list(canonical_phones or c.get("canonical_phones") or [])

    tri = triphone_keys(phones)
    bi = biphone_keys(phones)
    inv = phone_inventory_keys(phones)

    word = c.get("word") or c.get("target_word")
    text = c.get("grapheme") or c.get("candidate_text")

    return {
        "schema_version": "compat-from-candidate",
        "asset_id": c.get("asset_id") or f"{word or 'word'}__{text or 'candidate'}__{idx:04d}",
        "word": word,
        "target_word": word,
        "candidate_text": text,
        "grapheme": text,
        "phones": phones,
        "canonical_phones": canonical,
        "phone_key": phone_sequence_key(phones),
        "canonical_phone_key": phone_sequence_key(canonical),
        "triphone_keys": tri,
        "triphones": tri,
        "biphone_keys": bi,
        "phone_inventory": inv,
        "generation_mode": c.get("generation_mode", "global"),
        "level": c.get("level"),
        "morph_level": c.get("morph_level", c.get("level")),
        "distortion_level": c.get("distortion_level", c.get("level")),
        "phoneme_values": c.get("phoneme_values", [c.get("level")]),
        "phone_distance": c.get("phone_distance"),
        "phone_similarity": c.get("phone_similarity"),
        "neural_distance": c.get("neural_distance"),
        "neural_similarity": c.get("neural_similarity"),
        "suitability_score": c.get("suitability_score"),
        "voice": c.get("voice"),
        "voice_mode": c.get("voice_mode"),
        "gender": c.get("gender"),
        "source_phonemes": canonical,
        "output_phonemes": phones,
        "wav_path": c.get("wav_path"),
        "audio_path": c.get("audio_path") or c.get("wav_path"),
        "output_audio_path": c.get("output_audio_path") or c.get("audio_path") or c.get("wav_path"),
        "duration_info": c.get("duration_info"),
        "candidate": c,
    }


def load_assets(path: str | Path) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    payload = json.loads(Path(path).read_text())

    # Preferred new shapes.
    if isinstance(payload, dict):
        if isinstance(payload.get("blabber_assets"), list):
            return payload["blabber_assets"], payload
        if isinstance(payload.get("assets"), list):
            return payload["assets"], payload
        if isinstance(payload.get("library"), dict) and isinstance(payload["library"].get("assets"), list):
            return payload["library"]["assets"], payload

        # Backward compatibility: raw candidate list.
        if isinstance(payload.get("candidates"), list):
            canonical = payload.get("canonical_phones")
            assets = [
                normalize_asset_from_candidate(c, canonical_phones=canonical, idx=i)
                for i, c in enumerate(payload["candidates"])
            ]
            return assets, payload

    if isinstance(payload, list):
        # Either assets or candidates.
        assets = []
        for i, item in enumerate(payload):
            if "triphone_keys" in item or "phone_key" in item:
                assets.append(item)
            else:
                assets.append(normalize_asset_from_candidate(item, canonical_phones=None, idx=i))
        return assets, {"assets": assets}

    raise ValueError(f"Unsupported blabber library JSON shape: {path}")


def asset_score(
    asset: dict[str, Any],
    *,
    query_word: str | None,
    query_voice: str | None,
    query_phone_key: str | None,
    query_triphones: set[str],
    query_biphones: set[str],
    query_inventory: set[str],
    target_level: float | None,
    level_weight: float,
    global_search: bool = False,
) -> tuple[float, dict[str, float]]:
    score = 0.0
    details: dict[str, float] = {}

    if query_word:
        word_ok = 1.0 if asset.get("word") == query_word or asset.get("target_word") == query_word else 0.0
        details["word_match"] = word_ok
        if word_ok <= 0:
            return -1e9, details
        score += 2.0 * word_ok

    if query_voice:
        normalized_query_voice = normalize_voice_mode(query_voice)
        voice_ok = 1.0 if asset_voice_mode(asset) == normalized_query_voice else 0.0
        details["voice_match"] = voice_ok
        if voice_ok <= 0:
            return -1e9, details
        score += 0.5 * voice_ok

    asset_phone_key = asset.get("phone_key") or phone_sequence_key(asset.get("phones") or [])
    exact_phone = 1.0 if query_phone_key and asset_phone_key == query_phone_key else 0.0
    details["exact_phone_match"] = exact_phone

    asset_triphones = set(asset.get("triphone_keys") or asset.get("triphones") or [])
    tri_j = jaccard(query_triphones, asset_triphones)
    tri_recall = overlap_recall(query_triphones, asset_triphones)
    details["triphone_jaccard"] = tri_j
    details["triphone_recall"] = tri_recall

    asset_biphones = set(asset.get("biphone_keys") or [])
    bi_j = jaccard(query_biphones, asset_biphones)
    bi_recall = overlap_recall(query_biphones, asset_biphones)
    details["biphone_jaccard"] = bi_j
    details["biphone_recall"] = bi_recall

    asset_inventory = set(asset.get("phone_inventory") or asset.get("phones") or [])
    inv_j = jaccard(query_inventory, asset_inventory)
    details["phone_inventory_jaccard"] = inv_j

    if global_search:
        # In global temporal search, the canonical phone sequence is a word
        # constraint. The requested temporal distance should choose the level.
        score += 0.25 * exact_phone + 0.75 * tri_recall + 0.25 * bi_recall + 0.25 * inv_j
    else:
        score += 5.0 * exact_phone
        score += 3.0 * tri_j + 2.0 * tri_recall
        score += 1.0 * bi_j + 0.75 * bi_recall
        score += 0.75 * inv_j

    suitability = asset.get("suitability_score")
    if suitability is not None:
        details["suitability_score"] = float(suitability)
        score += (0.75 if global_search else 1.25) * float(suitability)

    neural_similarity = asset.get("neural_similarity")
    if neural_similarity is not None:
        details["neural_similarity"] = float(neural_similarity)
        score += (0.25 if global_search else 0.5) * float(neural_similarity)

    phone_similarity = asset.get("phone_similarity")
    if phone_similarity is not None:
        details["phone_similarity"] = float(phone_similarity)
        score += (0.25 if global_search else 0.5) * float(phone_similarity)

    if target_level is not None:
        level = asset.get("distortion_level", asset.get("morph_level", asset.get("level")))
        if level is not None:
            level_error = abs(float(level) - clamp_unit(target_level))
            level_score = max(0.0, 1.0 - level_error)
            details["level_score"] = level_score
            score += float(level_weight) * level_score

    details["total"] = score
    return score, details


def select_assets(
    assets: list[dict[str, Any]],
    *,
    word: str | None,
    phones: list[str],
    triphones: list[str],
    voice: str | None,
    target_level: float | None,
    min_level: float | None,
    max_level: float | None,
    top_k: int,
    level_weight: float,
    global_search: bool = False,
) -> list[dict[str, Any]]:
    query_phone_key = phone_sequence_key(phones) if phones else None

    if phones and not triphones:
        query_triphones = set(triphone_keys(phones))
    else:
        query_triphones = set(triphones)

    query_biphones = set(biphone_keys(phones)) if phones else set()
    query_inventory = set(phone_inventory_keys(phones)) if phones else set()

    ranked = []

    for asset in assets:
        level = asset.get("morph_level", asset.get("level"))
        if min_level is not None and level is not None and float(level) < min_level:
            continue
        if max_level is not None and level is not None and float(level) > max_level:
            continue

        score, details = asset_score(
            asset,
            query_word=word,
            query_voice=voice,
            query_phone_key=query_phone_key,
            query_triphones=query_triphones,
            query_biphones=query_biphones,
            query_inventory=query_inventory,
            target_level=target_level,
            level_weight=level_weight,
            global_search=global_search,
        )

        if score <= -1e8:
            continue

        ranked.append({
            "score": score,
            "score_details": details,
            "asset": asset,
        })

    ranked.sort(
        key=lambda r: (
            -r["score"],
            -(r["asset"].get("suitability_score") or 0),
            r["asset"].get("candidate_text") or "",
            r["asset"].get("asset_id") or "",
        )
    )
    return ranked[:top_k]


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("library_json")
    p.add_argument("--word", default=None)
    p.add_argument("--phones", nargs="*", default=None, help="Phone sequence, e.g. --phones N AH W OW")
    p.add_argument("--triphones", default=None, help="Comma-separated triphone keys.")
    p.add_argument("--voice", default=None)
    p.add_argument("--target-level", type=float, default=None)
    p.add_argument("--min-level", type=float, default=None)
    p.add_argument("--max-level", type=float, default=None)
    p.add_argument("--top-k", type=int, default=5)
    p.add_argument("--level-weight", type=float, default=None)
    p.add_argument(
        "--global-search",
        action="store_true",
        help="Treat --target-level as the primary whole-word temporal-distance selector.",
    )
    p.add_argument("--json-out", default=None)
    args = p.parse_args()

    phones = parse_phone_args(args.phones)
    triphones = parse_key_csv(args.triphones)

    if not phones and not triphones:
        raise SystemExit("Provide --phones or --triphones for triphone-style selection.")

    level_weight = float(args.level_weight) if args.level_weight is not None else (6.0 if args.global_search else 0.75)
    assets, payload = load_assets(args.library_json)
    selected = select_assets(
        assets,
        word=args.word,
        phones=phones,
        triphones=triphones,
        voice=args.voice,
        target_level=args.target_level,
        min_level=args.min_level,
        max_level=args.max_level,
        top_k=args.top_k,
        level_weight=level_weight,
        global_search=args.global_search,
    )

    result = {
        "library_json": str(args.library_json),
        "query": {
            "word": args.word,
            "phones": phones,
            "phone_key": phone_sequence_key(phones) if phones else None,
            "triphone_keys": triphone_keys(phones) if phones else triphones,
            "voice": args.voice,
            "target_level": args.target_level,
            "min_level": args.min_level,
            "max_level": args.max_level,
            "global_search": args.global_search,
            "level_weight": level_weight,
        },
        "result_count": len(selected),
        "results": selected,
    }

    if args.json_out:
        Path(args.json_out).write_text(json.dumps(result, indent=2))
        print(json.dumps({"json_out": args.json_out, "result_count": len(selected)}, indent=2))
    else:
        print(json.dumps(result, indent=2))


if __name__ == "__main__":
    import argparse
    main()
